# Data types or Data structures in python...
# 1.) Strings
# 2.) list
# 3.) Dictionaries
# These are super-flexible.

# String: these are the data types in python

name="mohit"            # This is one kind of String...
color='pink'            # This is second kind of String...
place='''India'''       # This is third kind of string...

# can add strings using "+" symbol...
print("I am "+name+" from "+place)              # Concatination

# Multiply the contents of the string...
print("Programmer-"*3)

# To find the length of the string...
length_of_place=len(place)
print("No. of character in place:",length_of_place)
